module.exports = {
	Alabama: 'https://www.google.com',
	Alaska: 'https://www.google.com',
	'American Samoa': 'https://www.google.com',
	Arizona: 'https://www.google.com',
	Arkansas: 'https://www.google.com',
	California: 'https://www.google.com',
	Colorado: 'https://www.google.com',
	Connecticut: 'https://www.google.com',
	Delaware: 'https://www.google.com',
	'District Of Columbia': 'https://www.google.com',
	'Federated States Of Micronesia': 'https://www.google.com',
	Florida: 'https://www.google.com',
	Georgia: 'https://www.google.com',
	Guam: 'https://www.google.com',
	Hawaii: 'https://www.google.com',
	Idaho: 'https://www.google.com',
	Illinois: 'https://www.google.com',
	Indiana: 'https://www.google.com',
	Iowa: 'https://www.google.com',
	Kansas: 'https://www.google.com',
	Kentucky: 'https://www.google.com',
	Louisiana: 'https://www.google.com',
	Maine: 'https://www.google.com',
	'Marshall Islands': 'https://www.google.com',
	Maryland: 'https://www.google.com',
	Massachusetts: 'https://www.google.com',
	Michigan: 'https://www.google.com',
	Minnesota: 'https://www.google.com',
	Mississippi: 'https://www.google.com',
	Missouri: 'https://www.google.com',
	Montana: 'https://www.google.com',
	Nebraska: 'https://www.google.com',
	Nevada: 'https://www.google.com',
	'New Hampshire': 'https://www.google.com',
	'New Jersey': 'https://www.google.com',
	'New Mexico': 'https://www.google.com',
	'New York': 'https://www.google.com',
	'North Carolina': 'https://www.google.com',
	'North Dakota': 'https://www.google.com',
	'Northern Mariana Islands': 'https://www.google.com',
	Ohio: 'https://www.google.com',
	Oklahoma: 'https://www.google.com',
	Oregon: 'https://www.google.com',
	Palau: 'https://www.google.com',
	Pennsylvania: 'https://www.google.com',
	'Puerto Rico': 'https://www.google.com',
	'Rhode Island': 'https://www.google.com',
	'South Carolina': 'https://www.google.com',
	'South Dakota': 'https://www.google.com',
	Tennessee: 'https://www.google.com',
	Texas: 'https://www.google.com',
	Utah: 'https://www.google.com',
	Vermont: 'https://www.google.com',
	'Virgin Islands': 'https://www.google.com',
	Virginia: 'https://www.google.com',
	Washington: 'https://www.google.com',
	'West Virginia': 'https://www.google.com',
	Wisconsin: 'https://www.google.com',
	Wyoming: 'https://www.google.com'
};
